# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      cronjob: "0 17 * * *"
    labels: ["infrastructure", "dependencies"]

updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "bun" # See documentation for possible values
    directory: "/" # Location of package manifests
    multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    multi-ecosystem-group: "infrastructure"
